---
title: "Poking the metadata"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
output: 
    html_document:
        keep_md: true
        toc: true
        toc_float: true
        theme: paper
        code_folding: hide
        df_print: paged
---
<style type="text/css">
    .main-container {
        max-width: 1800px !important;
        margin-left: auto;
        margin-right: auto;
    }
</style>

## Dependencies

```{r knitr}
library(knitr)
knitr::opts_chunk$set(
    dev=c('png', 'pdf', 'tiff'),
    dpi=300
)
```
Set up file locations + load dependenies
```{r file_locs, results=FALSE, message=FALSE, warning=FALSE}
library(here)
here::i_am('notebooks/pipeline.Rmd')
BASE_DIR <- here()
SCRIPT_DIR <- here('scripts')
source(file.path(SCRIPT_DIR, 'locations.R'))
source(file.path(SCRIPT_DIR, 'bootstrap_utils.R'))
library(tidyverse)
library(magrittr)
library(ggplot2)
library(devtools)
```

## Pipeline Example

Load Data
```{r load_data, results=FALSE, message=FALSE, warning=FALSE}
sample.metadata <- load_sample_metadata()
counts.matrix <- load_counts()
# model.specifcations <- load_model_specifications()
```
Load model+bootstrap parameters
```{r load_model}
# BATCH_HANDLING      <- '' or list of columns to group samples by for batching
N_BOOTSTRAPS         <- 20
CHUNK_SIZE           <- 5
model.specifications <- 
    c(
        file.path(MODEL_SPECIFICATIONS_DIR, 'SVA.only.model')
    ) %>%
    load_model_specifications()
model.specifications 
# all.model.specifications <- load_model_specifications()
```
Generate bootstraps (subsets of samples)
```{r generate_bootstrap_sample_lists}
# generate sample lists
model.specifications %>% generate_bootstraps()
```
Now Generate DEG results for 1 chunk of bootstraps
```{r generate_deg_results}
model.specifications %>% 
    rowwise() %>% 
    mutate(
        across(
            c(covariate.variables, ends_with('_samples')),
            ~ case_when(
                is.na(.x) ~ NA,
                TRUE ~ str_split(.x, pattern=',')
            )
        )
    ) %>% 
    ungroup() %>% 
    mutate(
        sampleID.variable='SampleID',
        gene_id_column='EnsemblID'
    ) %>% 
    pmap(
        # Save results for all contrasts, returns tibble, 1 row per contrast + deg results
        run_pipeline_on_chunk,
        # bootstrap.sample.lists,
        # results.dir,
        # chunk_id,
        # gene_id_column,
        force_redo=FALSE,
        return_data=TRUE,
        results_fnc=run_pipeline_on_chunk,
        sample.metadata=sample.metadata,
        counts.matrix=counts.matrix,
        .progress=TRUE
    )
```

## Reproducibility

```{r logging}
sessionInfo()
```

